### ISSUE TITLE
Bug report:  CRASH if launch without assets.

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor_2020#103]
**Describe the bug**
Crash during first launch.

**To Reproduce**
1. Run screenrecorder-rohit 6-27 .apk
2. Install RoboTutor (after uninstalling previous RoboTutor if any) with no assets.
3. Launch RoboTutor.
4. While loading glyphs.zip, it crashes.

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**
Crashing without assets isn't a big deal in and of itself, but interferes with replicating the HANG bug.

**Comment by madeleinvillegas** [comment]
Assume fixed
