### ISSUE TITLE
Feature request:  RoboTutor, RTFaceLogin, RoboFeel, etc., log stack traces for every ERROR

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor_2020#125]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
ERROR logged with insufficient information to debug.

Note: 
ERROR = uncaught exception logged as ERROR
CRASH = uncaught exception.

[app/src/main/java/cmu/xprize/robotutor/tutorengine/util/CrashHandler.java](https://github.com/RoboTutorLLC/RoboTutor_2020/blob/bfa7cc68b00edda06dac0eb8756b1fb81b5318ad/app/src/main/java/cmu/xprize/robotutor/tutorengine/util/CrashHandler.java):
public class CrashHandler implements Thread.UncaughtExceptionHandler {

[comp_logging/src/main/java/cmu/xprize/comp_logging/CErrorManager.java](https://github.com/RoboTutorLLC/RoboTutor_2020/blob/bfa7cc68b00edda06dac0eb8756b1fb81b5318ad/comp_logging/src/main/java/cmu/xprize/comp_logging/CErrorManager.java)

In https://github.com/RoboTutorLLC/RoboTutor_2020/blob/bfa7cc68b00edda06dac0eb8756b1fb81b5318ad/comp_logging/src/main/java/cmu/xprize/comp_logging/CLogManagerBase.java:

    public void postError(String Tag, String Msg, Exception e) {
        String packet;

        packet = "{" +
                "\"class\":\"ERROR\"," +
                "\"tag\":\"" + Tag + "\"," +
                "\"type\":\"Exception\"," +
                "\"time\":\"" + System.currentTimeMillis() + "\"," +
                "\"msg\":\"" + Msg + "\"," +
                "\"exception\":\"" + e.toString() + "\"" +
                "},\n";

        post(packet);
    }

**Describe the solution you'd like**
Log ERROR_message .txt like CRASH logs containing stack trace.
Do either in postError or in whoever calls postError.
Include sanitized error message in filename to make it easier to find instances of the same error message.
To avoid infinite loop, don't do it while already in the middle of logging another stack trace.

**Describe alternatives you've considered**
a. 1-stop shopping:  modify a single global ERROR function if it exists.
b. Cherrypick specific errors to stack-trace, e.g. in animator graph.
c. transform all source code to call an instrumented ERROR instead current ERROR.
d. In postError or whoever calls it:  dump stack trace if not already doing it. --> DO THIS

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Comment by JackMostow** [comment]
All-error stack traces implemented for RoboTutor_2020; next do for RTFaceLogin, RoboFeel

**Comment by madeleinvillegas** [comment]
Closing because Bhargav already implemented
