### ISSUE TITLE
Feature request:  Identify RoboTutor version by commit timestamp instead of number

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor_2020#129]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Version number is hard to maintain and auto-increment.

**Describe the solution you'd like**
Name version by commit timestamp instead of version number.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Comment by JackMostow** [comment]
Also adapt GitHub actions to generate apk for RoboTutor (and RoboFeel) same as for RTFaceLogin.

**Comment by rishideepc** [comment]
Hello Sir!

I have configured GitHub Actions for RoboTutor_2020. Now a new APK will be generated for RoboTutor_2020, every time a commit is pushed to the repo, and a new workflow is generated!

Thanks - Rishideep!

**Comment by JackMostow** [comment]
That was fast!  Great, but please address comments in code reviews.

**Comment by rishideepc** [comment]
Thank you Sir! I have addressed the questions in pull request #132.

**Comment by JackMostow** [comment]
Thanks!  I approved your changes, merged into development, and deleted the
branch.  - Jack
