### ISSUE TITLE
Fix most frequent crashes listed in the “Crashes by message, stack trace” tab of Session Table_v3.2_26Apr2019.xlsx

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor_2020#31]
Akash [ ] check the crashes through stack trace and find a way to fix some of the crashes listed in the “Crashes by message, stack trace” tab of [Session Table_v3.2_26Apr2019.xlsx](https://drive.google.com/file/d/1zl6_59ogmByhG-tOlRgq29TQulgsSJ0Q/view?usp=sharing), most frequent first.

Chengxuan fixed the two most frequent in an earlier list at [2018-12-21 SessionTable_WithCrash_AllSites_Except_(120, 125, 137).xlsx](https://drive.google.com/file/d/1UuXOodqabNhXekCbUBHVC69JHU2DirJR/view?usp=sharing):

- The most frequent CRASH message (1523 of 1725 = 88%) is a NullPointerException, 1502 of which have the same stack trace.

- The second most frequent (118 of 1725 = 7%) is StringIndexOutofBoundsException, all with the same stack trace.

Beware that this data came from version 2.7.7.1, aka “code drop 2”, so some of the line numbers may differ in newer versions.

**Comment by madeleinvillegas** [comment]
Outdated, closing the issue
