### ISSUE TITLE
RoboTutor version number doesn't distinguish versions

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor_2020#36]
@sansyrox - Distinct versions with the same version number (e.g. 3.4.2.1) are proliferating, making it hard to tell which version is running, e.g. while testing it or watching a screen video.  (Come to think of it, activity screen videos don't show the version number; only the activity menu screen does.
Is it possible to include this information on the screen display and in filenames of screen videos and log files?

Would auto-incrementing version number solve this problem by making version numbers unique?  I know you tried to implement this feature earlier but I don't recall what problem caused you to revert it.

**Comment by madeleinvillegas** [comment]
Merged, can close now

**Comment by JackMostow** [comment]
Instead of trying to auto-increment version numbers, we decided to identify versions by their commit timestamp.  So far we're using this scheme only for RTFaceLogin.
