### ISSUE TITLE
Bug report:  Travis-generated apks don't always match source code due to timing of merge wrt pull request

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor_2020#75]
**Describe the bug**
APK generated by pull request doesn't reflect subsequent changes to source code.

**To Reproduce**
1. Issue pull request.
2. Travis auto-generates APK.
3. Modify source code.
4. Merge branch into development.

**Expected behavior**
Apk at time of merge should match development branch source code

**Actual behavior**
It don't.

**Screenshots**

**Additional details**
How to fix?
a. Make Travis generate apk at time of merge.
b. Change settings to require what?

**Comment by madeleinvillegas** [comment]
Closing since we are migrating to GitHub Actions
