### ISSUE TITLE
Bug report:  fix automatic apk generation for FaceLogin

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor_2020#88]
**Describe the bug**
Travis automation breaks on generating FaceLogin apk.

**To Reproduce**
1. Pull request should invoke apk generation.
2. 
3. 
4. 

**Expected behavior**
Generate properly named apk for FaceLogin including sw for Swahili or en for English.

**Actual behavior**
Doesn't happen yet.  Manually generated apk doesn't specify language.

**Screenshots**

**Additional details**

**Comment by madeleinvillegas** [comment]
Already implemented using GitHub Actions
