### ISSUE TITLE
Bug report:  screen recording sometimes fails to stop audio recording when ASR starts listening

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor_2020#90]
**Describe the bug**
screen recording sometimes fails to stop audio recording when ASR starts listening

**To Reproduce**
1. Enable screen recording with audio in config.json include_audio_output_in_screen_recording.
2. Start screen recording service at start of session.
3. Start activity that listens.
4. 

**Expected behavior**
When it starts listening, it should start omitting audio from screen recording and just record siliently.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.
Sometimes it works.  Other times it continues recording audio, so the listening is disabled.

**Screenshots**

**Additional details**

**Comment by madeleinvillegas** [comment]
Closing since merged
